spring.application.name=TravelMate


spring.datasource.driver-class-name=org.postgresql.Driver
# 로컬 개발 환경 기준 URL (포트번호 5432, DB명 travelmate)
spring.datasource.url=jdbc:postgresql://localhost:5432/TravelMate
spring.datasource.username=ssafy
spring.datasource.password=ssafy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
# JPA가 실행하는 쿼리를 콘솔에 출력하고 보기 좋게 정렬
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

server.port=8080



# 절대 외부에 노출되면 안 되는 비밀키 (최소 32글자 이상)
jwt.secret=haadoop-pyramid-chomin-hoop-beagao-ouu-dakr-leassds-182kakaraootd-vegetable

# Access Token 만료시간 (예: 1시간 = 3600000ms)
jwt.access-expiration=3600000

# Refresh Token 만료시간 (예: 14일 = 1209600000ms)
jwt.refresh-expiration=1209600000

logging.level.com.yollo=debug




spring.data.redis.host=lucky-akita-133371.upstash.io
# 레디스 기본 포트
spring.data.redis.port=6379
# Upstash 콘솔에서 복사한 비밀번호(Token) 입력
spring.data.redis.password=gQAAAAAAAgj7AAIgcDJlMDAzODU4MzJiMTc0MzcyOWVlMGI1NDA4OGNkNzM0OA
# Upstash 필수 보안 설정 (SSL/TLS 활성화)
spring.data.redis.ssl.enabled=true


