spring.application.name=TravelMate
server.port=8080
embedding.server.url=http://127.0.0.1:8000



#logging.level.com.zaxxer.hikari=DEBUG
#비밀 키들은 모두 ENV 파일로 저장했습니다. 디폴트 값을 지정하지 않으면 크래시 납니다. (주의 ) 
# Spring Bootdml DataSourceAutoConfiguration 가 자동으로 (Hikari)DataSource를 빈으로 등록
spring.datasource.driver-class-name=org.postgresql.Driver
# 로컬 개발 환경 기준 URL (포트번호 5432, DB명 travelmate)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/travel_db}
spring.datasource.username=${DB_USERNAME:__}
spring.datasource.password=${DB_PASSWORD:__}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 엔티티 객체 수정 시 실 db 컬럼 자동 수정: update :validate는 도커로 
spring.jpa.hibernate.ddl-auto=validate
# JPA가 실행하는 쿼리를 콘솔에 출력하고 보기 좋게 정렬
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true





# 절대 외부에 노출되면 안 되는 비밀키 (최소 32글자 이상)
jwt.secret=${JWT_SECRET:TravelMateLocalDevSecretKeyMustBeAtLeast256Bits!}
# Access Token 만료시간 (예: 1시간 = 3600000ms)
jwt.access-expiration=3600000
# Refresh Token 만료시간 (예: 14일 = 1209600000ms)
jwt.refresh-expiration=1209600000
logging.level.com.yollo=debug




spring.data.redis.host=${REDIS_HOST:localhost}
# 레디스 기본 포트
spring.data.redis.port=${REDIS_PORT:6379}
# Upstash 콘솔에서 복사한 비밀번호(Token) 입력
spring.data.redis.password=${REDIS_PASSWORD:}
# Upstash 필수 보안 설정 (SSL/TLS 활성화)
spring.data.redis.ssl.enabled=true
kakao.rest-api-key=${KAKAO_REST_API_KEY:}


ollama.base-url =${OLLAMA-BASE-URL:http://localhost:11434}
ollama.model=qwen3:8b




