spring.application.name=TravelMate
logging.level.com.ssafy=debug
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 절대 외부에 노출되면 안 되는 비밀키 (최소 32글자 이상)
jwt.secret=haadoop-pyramid-chomin-hoop-beagao-ouu-dakr-leassds-182kakaraootd-vegetable

# Access Token 만료시간 (예: 1시간 = 3600000ms)
jwt.access-expiration=3600000

# Refresh Token 만료시간 (예: 14일 = 1209600000ms)
jwt.refresh-expiration=1209600000

